global:
  scrape_interval: 15s
  evaluation_interval: 15s
 
scrape_configs:
 
  # Surveiller les conteneurs Docker via cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
 
  # Surveiller Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
